services:
  keycloak_db:
    image: postgres:14
    env_file:
      - ./.env
    volumes:
      - ./postgres-keycloak-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    env_file:
      - ./.env
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    depends_on:
      - keycloak_db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env
  app:
    build:
      context: .
      dockerfile: ./api/container/Dockerfile
    env_file:
      - ./.env
    entrypoint: >
      sh -c "python /home/pyworker/app/src/main.py"
    volumes:
      - ./api:/home/pyworker/app:z
    ports:
      - "8000:8000"
